name: grocery_app_new_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  http: ^1.6.0
  pinput: ^6.0.1
  razorpay_flutter: ^1.4.0
  intl: ^0.20.2
  webview_flutter: ^4.13.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  image_picker: ^1.2.1

  # ✅ Firebase (Pinned for Ventura + Xcode 14.3.1 + Android)
  firebase_core: 2.25.2
  cloud_firestore: 4.15.2
  firebase_messaging: 14.7.10

  flutter_local_notifications: ^19.5.0
  lottie: ^3.1.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/grocery_items.json
    - assets/images/
    - assets/images/fruits/
    - assets/images/vegetables/
    - assets/images/dairy/
    - assets/images/grains/
    - assets/app_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_logo.png"
